version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.apache.maven.wagon:wagon-scm
    versions:
    - 3.4.2
  - dependency-name: org.apache.commons:commons-lang3
    versions:
    - "3.11"
